### ISSUE TITLE
[WIP] MVP Specifications

### ISSUE THREAD

**Issue by mictab** [mictab/Hacker-News-iOS#1]
WIP!

What should the MVP specifications be?

Initial thoughts:
- [x] Table View with cells containing title of story and author + # of points. Pressing one of these cells leads to the story being viewed using SFSafariViewController so it's in-app.
- [x] Usage of the Hacker News Firebase API for story retrieval.
- [x] Reading List for stories you'd like to read later
- [x] Favorite stories (of course you'd like to read some stories again!)
- [x] Manual updating of GET requests (??) by scrolling the view or pressing a refresh button. Perhaps there's a smarter more automatic solution.

Possible Extensions:
- Push notifications when new stories come out (needs to be checked if there's support)
- App settings (for eg. turning off push notifications if implemented)
- Viewing comments on stories (might require redesigning the detail view and perhaps there have a segue to a web view, who knows)
- [x] Night Mode
- [x] Search for stories by title
- [x] 3D Touch

**Comment by mictab** [comment]
@botronic

**Comment by botronic** [comment]
Lgtm!

**Comment by botronic** [comment]
For further extensions, night mode that makes the color scheme darker?

**Comment by mictab** [comment]
@botronic Maybe. You could check out https://github.com/Draveness/DKNightVersion or similar and think about how it would be implemented.

**Comment by TheForgot3n1** [comment]
Most people prefer efficient programs.
